services:
  contract-generator:
    build: .
    restart: unless-stopped
    environment:
      - PORT=5000
      - DEBUG=false
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-https://evolution.criativamaisdigital.com.br/message/sendMedia/criativa-suporte}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-D2D6BA530A73-4DF0-8AB3-78BD2C514C12}
      - PHONE_NUMBER=${PHONE_NUMBER:-556181435045@s.whatsapp.net}
    volumes:
      # Mount template file to ensure it's available
      - ./CONTRATO Casa da Ana.docx:/app/CONTRATO Casa da Ana.docx:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - contract-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  contract-network:
    driver: bridge 
