services:
  contract-generator:
    build: .
    restart: unless-stopped
    environment:
      - PORT=5000
      - DEBUG=false
      - WEBHOOK_URL=${WEBHOOK_URL:-https://webh.criativamaisdigital.com.br/webhook/c1d01bf8-6d34-44ee-9100-2923b5fb7876}
    volumes:
      # Mount template file to ensure it's available
      - ./CONTRATO Casa da Ana.docx:/app/CONTRATO Casa da Ana.docx:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - contract-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  contract-network:
    driver: bridge 
